### ISSUE TITLE
(Potential Enhancement) Make every meeting online - outlook preference setting for mac

### ISSUE THREAD

**Issue by MrHackermaine** [pbowden-msft/JamfManifests#1]
Seems to be relatively new, however we've been trying to tackle issues between MS Teams and Zoom meeting conflicts when it comes to creating a new meeting invite within outlook.

Reference Article: https://support.microsoft.com/en-us/office/make-every-meeting-online-70f9bda0-fd29-498b-9757-6709cc1c73f0#bkmk_turn-on-or-off

Do you know if there's a defined property we can control to force the checkbox setting on the client side?
![BB136A35-93A7-4AD8-BF66-E66294B18F54](https://user-images.githubusercontent.com/104221863/213304294-8764f858-3405-42f2-8993-3775d93e082a.jpeg)

**Comment by pbowden-msft** [comment]
@MrHackermaine thanks for reaching out. Unfortunately, these particular settings are stored in the mailbox on the service-side rather than in the local client preferences.
However, if you want to send an email to my work address (pbowden@microsoft.com), I can try and put you in contact with someone who might be able to help.
